### ISSUE TITLE
Sql script errors on upgrades from latest version

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/DNN.Survey#30]
## Describe the bug
The 09.00.00 sql script causes errors when upgrading from latest version and prevents upgrading the module

## Software Versions
- DNN: 08.00.04
- Module: 09.00.00

## To Reproduce
1. Install Survey 04.70.01
2. Try to upgrade to Survey 09.00.00

## Expected behavior
Upgrade should work fine

## Screenshots
![image](https://user-images.githubusercontent.com/6371568/56844822-aa153880-6884-11e9-8038-36de76176034.png)

## Additional context
I fixed some sql syntax on older scripts due to EVS warnings, but there are still some issues. @MaiklT can you try the steps above and take a look... I also added build scripts, so you can clone to either the DesktopModules folder of a site or in any location, building in release mode will produce the intaller in the Install subfolder.

Just in case, here is a build right now that has that issue.
[Dnn.Modules.Survey_09.00.00_Install.zip](https://github.com/DNNCommunity/DNN.Survey/files/3123493/Dnn.Modules.Survey_09.00.00_Install.zip)

Sidenote, I referenced Dnn 8 dll versions and change only 1 procedure in the upgrade code so that will make the module Dnn 8 and 9 compatible.

**Comment by MaiklT** [comment]
Daniel,
the only install package for DNN Survey 04.70.01 I found was marked as an RC. Version 04.70.00 was released with DNN 06.00.00, there was no official release of the Survey module later.
Anyway, when you upgrade from from Survey 04.60.00 to 04.70.xx (in any DNN version from 06.00.00!), you get a configuration error, because someone "forgot" to remove the code subdirectory from the web.config (I wonder how this could pass the quality checks!):

`Line 188:      <codeSubDirectories>`  
**`Line 189:        <add directoryName="Survey" />`**  
`Line 190:      </codeSubDirectories>`  

There was no new SQL script in any Survey 04.70.xx version, and I could upgrade from Survey 04.70.00 and 04.70.01 to 09.00.00 without a problem (except the one mentioned above that appears when you upgrade to DNN 04.07.xx).
I then tried to upgrade from a fresh install of 04.70.01 - also there, no problem.

Which installation pack did you try? I took the RC5 that I included in the pull request on April 11th ( see also [https://github.com/MaiklT/DNN.Survey/releases](https://github.com/MaiklT/DNN.Survey/releases) )

**Comment by MaiklT** [comment]
OK, got it. The ViewOrder column in the Surveys table can contain NULL values, and if there are some the script fails. Solution: change file 09.00.00.SqlDataProvider, line 32 from
`   ViewOrder,`
to
`   ROW_NUMBER() OVER (PARTITION BY ModuleID ORDER BY ViewOrder, SurveyID) AS [ViewOrder]`

Also check line 75 and line 180 - the column name in the old Surveys table was "CreatedByUser", not "CreatedByUserID"

(just as a reminder for myself...)

**Comment by MaiklT** [comment]
Also check line 75 - the column name in the old Surveys table was "CreatedByUser", not "CreatedByUserID"
